import { useCallback, useEffect, useState, type FormEvent, type MouseEvent } from "react";
import { ApiError, changePassword, getCurrentUser, login, logout, type CurrentUser } from "./api.js";
import "./app.css";
import { CreateTicketPage } from "./CreateTicketPage.js";
import { MyTicketsPage } from "./MyTicketsPage.js";
import { TicketDetailPage } from "./TicketDetailPage.js";

function ticketIdFromPath(path: string) { return path.match(/^\/tickets\/([^/]+)$/)?.[1] ?? null; }
function LoginPage({ onLogin }: { onLogin:(user:CurrentUser)=>void }) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(event:FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { onLogin(await login(email,password)); } catch (reason) { setPassword(""); setError(reason instanceof ApiError ? reason.message : "Sign in is unavailable. Try again."); } finally { setBusy(false); } }
  return <main className="selection-page"><section className="selection-card" aria-labelledby="login-title"><p className="eyebrow">TokTickIT IT Service Desk</p><h1 id="login-title">Sign in</h1><p>Use your TokTickIT account to continue.</p>{error&&<div className="feedback-panel feedback-panel-error" role="alert"><h2>Sign in failed</h2><p>{error}</p><p>Contact your TokTickIT administrator if you cannot sign in.</p></div>}<form className="selection-form" onSubmit={submit} aria-busy={busy}><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="username" required maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Password</label><input id="password" type={showPassword?"text":"password"} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/><button className="text-button" type="button" aria-pressed={showPassword} onClick={()=>setShowPassword(!showPassword)}>{showPassword?"Hide password":"Show password"}</button><button className="primary-button" disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></section></main>;
}
function ChangePasswordPage({ user,onChanged,onLogout }:{user:CurrentUser;onChanged:(u:CurrentUser)=>void;onLogout:()=>void}) {
  const [current,setCurrent]=useState(""); const [next,setNext]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{onChanged(await changePassword(current,next,confirm));}catch(reason){setCurrent("");setNext("");setConfirm("");setError(reason instanceof ApiError?reason.message:"Password change is unavailable. Try again.");}finally{setBusy(false)}}
  return <main className="selection-page"><section className="selection-card"><p className="eyebrow">Initial account security</p><h1>Change your password</h1><p>{user.displayName}, create a private password before using TokTickIT.</p>{error&&<div className="feedback-panel feedback-panel-error" role="alert"><p>{error}</p></div>}<form className="selection-form" onSubmit={submit} aria-busy={busy}><label htmlFor="current-password">Current password</label><input id="current-password" type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/><label htmlFor="new-password">New password</label><input id="new-password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={next} onChange={e=>setNext(e.target.value)}/><p className="helper-text">12–128 characters. Spaces and Unicode are allowed.</p><label htmlFor="confirm-password">Confirm new password</label><input id="confirm-password" type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="primary-button" disabled={busy}>{busy?"Changing password…":"Change password"}</button><button className="text-button" type="button" onClick={onLogout}>Sign out</button></form></section></main>;
}
function AppShell({user,currentPath,onNavigate,onLogout}:{user:CurrentUser;currentPath:string;onNavigate:(p:string)=>void;onLogout:()=>void}) {
  const [menu,setMenu]=useState(false); const ticketId=ticketIdFromPath(currentPath);
  function link(event:MouseEvent<HTMLAnchorElement>,path:string){event.preventDefault();setMenu(false);onNavigate(path)}
  const unavailable=()=>void onLogout();
  return <div className="app-layout"><header className="app-header"><a className="brand" href="/tickets" aria-label="TokTickIT home" onClick={e=>link(e,"/tickets")}><span>TokTickIT</span><small>IT Service Desk</small></a><button className="mobile-nav-toggle secondary-button" type="button" aria-expanded={menu} aria-controls="primary-navigation" onClick={()=>setMenu(!menu)}>Menu</button><nav className={`primary-navigation${menu?" primary-navigation-open":""}`} id="primary-navigation" aria-label="Primary navigation"><a href="/tickets" aria-current={currentPath==="/tickets"?"page":undefined} onClick={e=>link(e,"/tickets")}>My Tickets</a><a href="/tickets/new" aria-current={currentPath==="/tickets/new"?"page":undefined} onClick={e=>link(e,"/tickets/new")}>Create Ticket</a></nav><div className="requester-context"><span className="context-label">Signed in · Requester</span><strong>{user.displayName}</strong><button className="text-button" type="button" onClick={onLogout}>Sign out</button></div></header><main className="app-content">{currentPath==="/tickets/new"?<CreateTicketPage requester={user} onRequesterUnavailable={unavailable}/>:ticketId?<TicketDetailPage key={ticketId} requester={user} ticketId={ticketId} onNavigate={onNavigate} onRequesterUnavailable={unavailable}/>:<MyTicketsPage requester={user} onNavigate={onNavigate} onRequesterUnavailable={unavailable}/>}</main></div>;
}
export default function App(){const [state,setState]=useState<"loading"|"anonymous"|"ready">("loading");const[user,setUser]=useState<CurrentUser|null>(null);const[path,setPath]=useState(window.location.pathname);
  const navigate=useCallback((next:string)=>{if(location.pathname!==next)history.pushState({},"",next);setPath(next)},[]);
  useEffect(()=>{getCurrentUser().then(u=>{setUser(u);setState("ready")}).catch(()=>setState("anonymous"))},[]);
  useEffect(()=>{const pop=()=>setPath(location.pathname);addEventListener("popstate",pop);return()=>removeEventListener("popstate",pop)},[]);
  const signedOut=useCallback(async()=>{try{await logout()}catch{}setUser(null);setState("anonymous");navigate("/login")},[navigate]);
  if(state==="loading")return <main className="selection-page"><section className="selection-card" aria-busy="true"><h1>Loading TokTickIT…</h1></section></main>;
  if(state==="anonymous"||!user)return <LoginPage onLogin={u=>{setUser(u);setState("ready");navigate(u.mustChangePassword?"/change-password":"/tickets")}}/>;
  if(user.mustChangePassword)return <ChangePasswordPage user={user} onChanged={u=>{setUser(u);navigate("/tickets")}} onLogout={()=>void signedOut()}/>;
  if(user.role!=="REQUESTER")return <main className="selection-page"><section className="selection-card"><h1>{user.role==="IT_STAFF"?"IT Staff":"Administrator"}</h1><p>Your role workspace will be delivered in the next Lab 3 Issues.</p><button className="primary-button" onClick={()=>void signedOut()}>Sign out</button></section></main>;
  return <AppShell user={user} currentPath={path.startsWith("/tickets")?path:"/tickets"} onNavigate={navigate} onLogout={()=>void signedOut()}/>;
}
