import { useCallback,useEffect,useRef,useState } from "react";
import { ApiError,claimStaffTicket,getStaffAttachmentContent,getStaffOwners,getStaffTicket,setStaffTicketOwner,setStaffTicketPriority,setStaffTicketStatus,statusLabel,type RequestedPriority,type StaffOwner,type StaffTicketDetail,type TicketStatus } from "./api.js";
import { CommunicationPanel } from "./CommunicationPanel.js";

const transition:Record<TicketStatus,TicketStatus[]>={NEW:["OPEN","CANCELLED"],OPEN:["IN_PROGRESS","WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"],IN_PROGRESS:["WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"],WAITING_FOR_REQUESTER:["IN_PROGRESS","RESOLVED","CANCELLED"],RESOLVED:["CLOSED","REOPENED"],CLOSED:["REOPENED"],REOPENED:["IN_PROGRESS","WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"],CANCELLED:[]};
const terminal=(status:TicketStatus)=>["RESOLVED","CLOSED","CANCELLED"].includes(status);
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

export function StaffTicketDetailPage({ticketId,onNavigate}:{ticketId:string;onNavigate:(path:string)=>void}){
 const [ticket,setTicket]=useState<StaffTicketDetail|null>(null),[owners,setOwners]=useState<StaffOwner[]>([]),[state,setState]=useState<"loading"|"ready"|"error"|"missing">("loading"),[busy,setBusy]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [owner,setOwner]=useState(""),[priority,setPriority]=useState<RequestedPriority>("MEDIUM"),[status,setStatus]=useState<TicketStatus>("NEW"),[confirmed,setConfirmed]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
 const sync=(next:StaffTicketDetail)=>{setTicket(next);setOwner(next.owner?String(next.owner.id):"");setPriority(next.itPriority);setStatus(transition[next.status][0]??next.status);setConfirmed(false)};
 const load=useCallback(async()=>{setState("loading");setError("");try{const [detail,list]=await Promise.all([getStaffTicket(ticketId),getStaffOwners()]);sync(detail);setOwners(list.items);setState("ready")}catch(reason){setState(reason instanceof ApiError&&reason.status===404?"missing":"error");setError(reason instanceof ApiError?reason.message:"Ticket detail could not be loaded. Try again.")}},[ticketId]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(state==="ready")heading.current?.focus()},[state]);
 async function action(label:string,run:(current:StaffTicketDetail)=>Promise<StaffTicketDetail>){if(!ticket||busy)return;setBusy(label);setError("");setSuccess("");try{const next=await run(ticket);sync(next);setSuccess(`${label} saved.`)}catch(reason){setError(reason instanceof ApiError?reason.message:`${label} could not be saved. Try again.`)}finally{setBusy("")}}
 async function download(id:number){if(!ticket)return;setBusy(`attachment-${id}`);setError("");try{const content=await getStaffAttachmentContent(ticket.id,id),url=URL.createObjectURL(content.blob),link=document.createElement("a");link.href=url;link.download=content.filename;link.click();URL.revokeObjectURL(url)}catch(reason){setError(reason instanceof ApiError?reason.message:"Attachment could not be downloaded. Try again.")}finally{setBusy("")}}
 if(state==="loading")return <section className="detail-state" aria-busy="true"><h1>Loading Ticket Detail…</h1></section>;
 if(state!=="ready"||!ticket)return <section className="detail-state"><h1>{state==="missing"?"Ticket unavailable":"Ticket Detail unavailable"}</h1><p role="alert">{error}</p><button className="secondary-button" onClick={()=>void load()}>Retry</button></section>;
 const transitions=transition[ticket.status];
 return <div className="staff-detail-page">
  <a href="/staff/tickets" onClick={e=>{e.preventDefault();onNavigate("/staff/tickets")}}>← Back to Ticket Queue</a>
  <header className="ticket-detail-heading"><div><p className="eyebrow">Staff Ticket Detail</p><h1 ref={heading} tabIndex={-1}>{ticket.ticketNumber}</h1><p>{ticket.summary}</p></div><span className={`status-badge status-${ticket.status.toLowerCase().replaceAll("_","-")}`}>{statusLabel(ticket.status)}</span></header>
  {error&&<div className="feedback-panel feedback-panel-error" role="alert"><p>{error}</p>{error.toLowerCase().includes("changed")&&<button className="secondary-button" onClick={()=>void load()}>Reload Ticket</button>}</div>}{success&&<p className="success-message" role="status">{success}</p>}
  <section className="detail-panel"><h2>Ticket context</h2><dl className="detail-grid"><div><dt>Requester</dt><dd>{ticket.requester.displayName} ({ticket.requester.email})</dd></div><div><dt>Category</dt><dd>{ticket.category.name}</dd></div><div><dt>Related System</dt><dd>{ticket.relatedSystem.name}</dd></div><div><dt>Requested Priority</dt><dd>{ticket.requestedPriority}</dd></div><div><dt>Owner</dt><dd>{ticket.owner?.displayName??"Unassigned"}</dd></div><div><dt>Updated</dt><dd>{date(ticket.updatedAt)}</dd></div></dl><h3>Description</h3><p className="preserve-text">{ticket.description}</p>{ticket.requesterResolutionIndicatedAt&&<p className="resolution-indication">Requester indicated apparent resolution at {date(ticket.requesterResolutionIndicatedAt)}.</p>}</section>
  <section className="detail-panel"><h2>Operations</h2>{terminal(ticket.status)&&<p>Assignment and IT Priority are locked while this Ticket is {statusLabel(ticket.status)}.</p>}<div className="operation-grid">
   <form onSubmit={e=>{e.preventDefault();void action("Owner",t=>setStaffTicketOwner(t.id,owner?Number(owner):null,t.version))}}><label htmlFor="detail-owner">Owner</label><select id="detail-owner" value={owner} disabled={terminal(ticket.status)||!!busy} onChange={e=>setOwner(e.target.value)}><option value="">Unassigned</option>{owners.map(x=><option value={x.id} key={x.id}>{x.displayName}</option>)}</select><button className="secondary-button" disabled={terminal(ticket.status)||!!busy}>Save Owner</button>{!ticket.owner&&<button type="button" className="primary-button" disabled={terminal(ticket.status)||!!busy} onClick={()=>void action("Claim",t=>claimStaffTicket(t.id,t.version))}>{busy==="Claim"?"Claiming…":"Claim Ticket"}</button>}</form>
   <form onSubmit={e=>{e.preventDefault();void action("IT Priority",t=>setStaffTicketPriority(t.id,priority,t.version))}}><label htmlFor="detail-priority">IT Priority</label><select id="detail-priority" value={priority} disabled={terminal(ticket.status)||!!busy} onChange={e=>setPriority(e.target.value as RequestedPriority)}>{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select><button className="secondary-button" disabled={terminal(ticket.status)||!!busy}>Save IT Priority</button></form>
   <form onSubmit={e=>{e.preventDefault();if(["RESOLVED","CLOSED","CANCELLED"].includes(status)&&!confirmed){setError("Confirm the terminal status change before saving.");return}void action("Status",t=>setStaffTicketStatus(t.id,status,t.version))}}><label htmlFor="detail-status">Status</label><select id="detail-status" value={status} disabled={!transitions.length||!!busy} onChange={e=>{setStatus(e.target.value as TicketStatus);setConfirmed(false)}}>{transitions.length?transitions.map(x=><option value={x} key={x}>{statusLabel(x)}</option>):<option value={ticket.status}>No transitions available</option>}</select>{["RESOLVED","CLOSED","CANCELLED"].includes(status)&&<label className="confirmation"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I understand this is a terminal status.</label>}<button className="secondary-button" disabled={!transitions.length||!!busy}>Save Status</button></form>
  </div></section>
  <section className="detail-panel attachment-section"><h2>Attachments</h2>{ticket.attachments.filter(a=>!a.removed).length===0?<p>No active Attachments.</p>:<ul className="detail-attachment-list">{ticket.attachments.filter(a=>!a.removed).map(a=><li key={a.id}><strong>{a.originalName}</strong><span>{a.mimeType} · {a.sizeBytes} bytes</span><button className="secondary-button" disabled={!!busy} onClick={()=>void download(a.id)}>{busy===`attachment-${a.id}`?"Downloading…":"Download"}</button></li>)}</ul>}</section>
  <CommunicationPanel ticketId={ticket.id} kind="comments"/><CommunicationPanel ticketId={ticket.id} kind="notes"/>
 </div>;
}
