import { useCallback,useEffect,useRef,useState } from "react";
import { ApiError,claimStaffTicket,getStaffAttachmentContent,getStaffOwners,getStaffTicket,setStaffTicketOwner,setStaffTicketPriority,setStaffTicketStatus,statusLabel,type RequestedPriority,type StaffOwner,type StaffTicketDetail,type TicketStatus } from "./api.js";
import { CommunicationPanel } from "./CommunicationPanel.js";
import { ActionsTaken } from "./ActionsTaken.js";
import { WorkflowHistory } from "./WorkflowHistory.js";
import { matchingSummary, readyToResolve, ResolutionChecklist } from "./ResolutionChecklist.js";
import type { CurrentUser, ActionPage } from "./api.js";

const transition:Record<TicketStatus,TicketStatus[]>={NEW:["OPEN","CANCELLED"],OPEN:["IN_PROGRESS","WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"],IN_PROGRESS:["WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"],WAITING_FOR_REQUESTER:["IN_PROGRESS","RESOLVED","CANCELLED"],RESOLVED:["CLOSED","REOPENED"],CLOSED:["REOPENED"],REOPENED:["IN_PROGRESS","WAITING_FOR_REQUESTER","RESOLVED","CANCELLED"],CANCELLED:[]};
const terminal=(status:TicketStatus)=>["RESOLVED","CLOSED","CANCELLED"].includes(status);
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

export function StaffTicketDetailPage({ticketId,onNavigate,currentUser,linkedActionId}:{ticketId:string;onNavigate:(path:string)=>void;currentUser?:CurrentUser;linkedActionId?:string|null}){
 const [actionsBusy,setActionsBusy]=useState(false);
 const [summary,setSummary]=useState<ActionPage|null>(null),[reconcile,setReconcile]=useState(false);
 const [ticket,setTicket]=useState<StaffTicketDetail|null>(null),[owners,setOwners]=useState<StaffOwner[]>([]),[state,setState]=useState<"loading"|"ready"|"error"|"missing">("loading"),[busy,setBusy]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [owner,setOwner]=useState(""),[priority,setPriority]=useState<RequestedPriority>("MEDIUM"),[status,setStatus]=useState<TicketStatus|"">(""),[confirmed,setConfirmed]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
 const generation=useRef(0),currentTicketId=useRef(ticketId);currentTicketId.current=ticketId;
 const statusHeading=useRef<HTMLHeadingElement>(null),lastStatus=useRef<{ticketId:string;status:TicketStatus}|null>(null);
 const sync=(next:StaffTicketDetail)=>{setTicket(next);setOwner(next.owner?String(next.owner.id):"");setPriority(next.itPriority);setStatus("");setConfirmed(false)};
 const load=useCallback(async()=>{const request=++generation.current;setState("loading");setError("");setSuccess("");setSummary(null);setReconcile(false);try{const [detail,list]=await Promise.all([getStaffTicket(ticketId),getStaffOwners()]);if(request!==generation.current||currentTicketId.current!==ticketId)return;sync(detail);setOwners(list.items);setState("ready")}catch(reason){if(request!==generation.current||currentTicketId.current!==ticketId)return;setState(reason instanceof ApiError&&reason.status===404?"missing":"error");setError(reason instanceof ApiError?reason.message:"Ticket detail could not be loaded. Try again.")}},[ticketId]);
 useEffect(()=>{void load();return()=>{generation.current++}},[load]);useEffect(()=>{if(state==="ready")heading.current?.focus()},[state]);
 useEffect(()=>{if(state!=="ready"||!ticket||String(ticket.id)!==ticketId)return;if(lastStatus.current?.ticketId===ticketId&&lastStatus.current.status==="NEW"&&ticket.status!=="NEW")statusHeading.current?.focus();lastStatus.current={ticketId,status:ticket.status}},[state,ticket?.status,ticketId]);
 async function action(label:string,run:(current:StaffTicketDetail)=>Promise<StaffTicketDetail>){if(!ticket||busy||actionsBusy||reconcile||String(ticket.id)!==ticketId)return;const request=generation.current,requestedId=ticketId;setBusy(label);setError("");setSuccess("");setSummary(null);try{const next=await run(ticket);if(request!==generation.current||currentTicketId.current!==requestedId)return;sync(next);setSuccess(`${label} saved.`)}catch(reason){if(request===generation.current&&currentTicketId.current===requestedId){const unknown=!(reason instanceof ApiError)||reason.status>=500;if(unknown||reason instanceof ApiError&&reason.code==="VERSION_CONFLICT")setReconcile(true);setError(unknown?`${label} save outcome unknown. Reload Ticket and review its current state before saving again.`:reason.message)}}finally{if(request===generation.current&&currentTicketId.current===requestedId)setBusy("")}}
 async function download(id:number){if(!ticket||String(ticket.id)!==ticketId)return;const request=generation.current,requestedId=ticketId;setBusy(`attachment-${id}`);setError("");try{const content=await getStaffAttachmentContent(ticket.id,id);if(request!==generation.current||currentTicketId.current!==requestedId)return;const url=URL.createObjectURL(content.blob),link=document.createElement("a");link.href=url;link.download=content.filename;link.click();URL.revokeObjectURL(url)}catch(reason){if(request===generation.current&&currentTicketId.current===requestedId)setError(reason instanceof ApiError?reason.message:"Attachment could not be downloaded. Try again.")}finally{if(request===generation.current&&currentTicketId.current===requestedId)setBusy("")}}
 if(state==="loading"||(ticket&&String(ticket.id)!==ticketId))return <section className="detail-state" aria-busy="true"><h1>Loading Ticket Detail…</h1></section>;
 if(state!=="ready"||!ticket)return <section className="detail-state"><h1>{state==="missing"?"Ticket unavailable":"Ticket Detail unavailable"}</h1><p role="alert">{error}</p><button className="secondary-button" onClick={()=>void load()}>Retry</button></section>;
 const transitions=transition[ticket.status];
 const statusAllowed=status!==""&&transitions.includes(status);
 const parentBusy=!!busy||reconcile;
 const checklist=parentBusy||actionsBusy?null:summary;
 const statusBlocked=status==="RESOLVED"?!readyToResolve(ticket,checklist):status==="CANCELLED"?(!matchingSummary(ticket,checklist)||checklist!.resolutionGate.unfinishedCount>0):false;
 const opening=ticket.status==="NEW";
 const statusPanel=<section className="detail-panel status-workflow-panel" aria-labelledby="ticket-status-stage-title">
  <h2 id="ticket-status-stage-title" ref={statusHeading} tabIndex={-1}>{opening?"Open ticket":ticket.status==="CANCELLED"?"Ticket status":"Update ticket status"}</h2>
  {opening&&<p>Open this New ticket to begin the workflow. Progress statuses become available after opening.</p>}
  <form className="ticket-status-form" onSubmit={e=>{e.preventDefault();if(!statusAllowed||statusBlocked||parentBusy||actionsBusy)return;if(["RESOLVED","CLOSED","CANCELLED"].includes(status)&&!confirmed){setError("Confirm the terminal status change before saving.");return}void action("Status",t=>setStaffTicketStatus(t.id,status,t.version))}}>
   <div className="current-status-panel" role="group" aria-label="Current status"><span>Current status</span><strong className={`status-badge status-${ticket.status.toLowerCase().replaceAll("_","-")}`}>{statusLabel(ticket.status)}</strong></div>
   <div className="status-target-controls">
    <label htmlFor="detail-status">{opening?"Choose an action":"Change status to"}</label>
    <select id="detail-status" value={status} aria-describedby="detail-status-help" disabled={!transitions.length||parentBusy||actionsBusy} onChange={e=>{setStatus(e.target.value as TicketStatus|"");setConfirmed(false)}}>
     <option value="">{opening?"Choose an action…":transitions.length?"Choose a new status…":"No transitions available"}</option>
     {transitions.map(x=><option value={x} key={x}>{opening?x==="OPEN"?"Open Ticket":"Cancel Ticket":statusLabel(x)}</option>)}
    </select>
    <p id="detail-status-help" className="status-change-help">{statusAllowed?`${statusLabel(ticket.status)} → ${statusLabel(status)}. Not saved yet.`:opening?"Choose Open Ticket to start, or Cancel Ticket if the request is not needed.":transitions.length?"Choose a new status, then Save Status. The current status stays unchanged until the save succeeds.":"This Ticket is cancelled. No further status changes are available."}</p>
    {["RESOLVED","CLOSED","CANCELLED"].includes(status)&&<label className="confirmation"><input type="checkbox" disabled={parentBusy||actionsBusy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I understand this is a terminal status.</label>}
    {["RESOLVED","CLOSED","CANCELLED","REOPENED"].includes(status)&&<p className="status-change-help">{status==="RESOLVED"?"Resolution requires the current checklist to pass.":status==="CLOSED"?"Closing retains the formal resolution and history.":status==="CANCELLED"?"Cancellation is permanent and requires no active actions.":"Reopening starts a new cycle and clears the advisory indication."}</p>}
    <button className={opening&&status!=="CANCELLED"?"primary-button":"secondary-button"} disabled={!statusAllowed||parentBusy||actionsBusy||statusBlocked||(["RESOLVED","CLOSED","CANCELLED"].includes(status)&&!confirmed)}>{opening?status==="CANCELLED"?"Cancel Ticket":"Open Ticket":"Save Status"}</button>
   </div>
  </form>
 </section>;
 return <div className="staff-detail-page">
  <a href="/staff/tickets" onClick={e=>{e.preventDefault();onNavigate("/staff/tickets")}}>← Back to Ticket Queue</a>
  <header className="ticket-detail-heading"><div><p className="eyebrow">Staff Ticket Detail</p><h1 ref={heading} tabIndex={-1}>{ticket.ticketNumber}</h1><p>{ticket.summary}</p></div><span className={`status-badge status-${ticket.status.toLowerCase().replaceAll("_","-")}`}>{statusLabel(ticket.status)}</span></header>
  {error&&<div className="feedback-panel feedback-panel-error" role="alert"><p>{error}</p>{(reconcile||error.toLowerCase().includes("changed"))&&<button className="secondary-button" onClick={()=>void load()}>Reload Ticket</button>}</div>}{success&&<p className="success-message" role="status">{success}</p>}
  <section className="detail-panel"><h2>Ticket context</h2><dl className="detail-grid"><div><dt>Requester</dt><dd>{ticket.requester.displayName} ({ticket.requester.email})</dd></div><div><dt>Category</dt><dd>{ticket.category.name}</dd></div><div><dt>Related System</dt><dd>{ticket.relatedSystem.name}</dd></div><div><dt>Requested Priority</dt><dd>{ticket.requestedPriority}</dd></div><div><dt>Owner</dt><dd>{ticket.owner?.displayName??"Unassigned"}</dd></div><div><dt>Updated</dt><dd>{date(ticket.updatedAt)}</dd></div></dl><h3>Description</h3><p className="preserve-text">{ticket.description}</p>{ticket.requesterResolutionIndicatedAt&&<p className="resolution-indication">Requester indicated apparent resolution at {date(ticket.requesterResolutionIndicatedAt)}.</p>}</section>
  <div className="workflow-controls">{opening&&statusPanel}<ResolutionChecklist ticket={ticket} summary={checklist}/>
  <section className="detail-panel"><h2>Operations</h2>{terminal(ticket.status)&&<p>Assignment and IT Priority are locked while this Ticket is {statusLabel(ticket.status)}.</p>}<div className="operation-grid">
   <form onSubmit={e=>{e.preventDefault();void action("Owner",t=>setStaffTicketOwner(t.id,owner?Number(owner):null,t.version))}}><label htmlFor="detail-owner">Owner</label><select id="detail-owner" value={owner} disabled={terminal(ticket.status)||parentBusy||actionsBusy} onChange={e=>setOwner(e.target.value)}><option value="">Unassigned</option>{owners.map(x=><option value={x.id} key={x.id}>{x.displayName}</option>)}</select><button className="secondary-button" disabled={terminal(ticket.status)||parentBusy||actionsBusy}>Save Owner</button>{!ticket.owner&&<button type="button" className="primary-button" disabled={terminal(ticket.status)||parentBusy||actionsBusy} onClick={()=>void action("Claim",t=>claimStaffTicket(t.id,t.version))}>{busy==="Claim"?"Claiming…":"Claim Ticket"}</button>}</form>
   <form onSubmit={e=>{e.preventDefault();void action("IT Priority",t=>setStaffTicketPriority(t.id,priority,t.version))}}><label htmlFor="detail-priority">IT Priority</label><select id="detail-priority" value={priority} disabled={terminal(ticket.status)||parentBusy||actionsBusy} onChange={e=>setPriority(e.target.value as RequestedPriority)}>{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select><button className="secondary-button" disabled={terminal(ticket.status)||parentBusy||actionsBusy}>Save IT Priority</button></form>
  </div></section>{!opening&&statusPanel}</div>
  <section className="detail-panel attachment-section"><h2>Attachments</h2>{ticket.attachments.filter(a=>!a.removed).length===0?<p>No active Attachments.</p>:<ul className="detail-attachment-list">{ticket.attachments.filter(a=>!a.removed).map(a=><li key={a.id}><strong>{a.originalName}</strong><span>{a.mimeType} · {a.sizeBytes} bytes</span><button className="secondary-button" disabled={!!busy} onClick={()=>void download(a.id)}>{busy===`attachment-${a.id}`?"Downloading…":"Download"}</button></li>)}</ul>}</section>
  <ActionsTaken ticket={ticket} staff userId={currentUser?.id??0} actorName={currentUser?.displayName??"the signed-in user"} linkedActionId={linkedActionId} externalBusy={parentBusy} onBusyChange={setActionsBusy} onParentUpdated={setTicket} onSummaryChange={setSummary}/>
  <WorkflowHistory key={`${ticket.id}:${currentUser?.id??0}`} ticketId={ticket.id} version={ticket.version}/>
  <CommunicationPanel ticketId={ticket.id} kind="comments"/><CommunicationPanel ticketId={ticket.id} kind="notes"/>
 </div>;
}
