import { useEffect, useRef, useState } from "react";
import { ApiError } from "./api.js";
import { getActionWork, type WorkPage, type WorkQuery } from "./dashboard-api.js";
import { readListSearch, listSearch } from "./list-url.js";
export const defaultWorkQuery: WorkQuery = { assignedTo: "", performedBy: "", stateGroup: "", state: "", performedSince: "", performedUntil: "", page: 1, pageSize: 20 };
export function StaffActionsPage({ urlSearch, onNavigate }: { urlSearch: string; onNavigate: (path: string) => void }) {
  const parsed = readListSearch(urlSearch, defaultWorkQuery, "actions"), [result, setResult] = useState<WorkPage | null>(null), [busy, setBusy] = useState(true), [error, setError] = useState(""), [refresh, setRefresh] = useState(0);
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus(); }, []);
  useEffect(() => { let current = true; setResult(null); setError(""); if (parsed.error) { setBusy(false); return; } setBusy(true);
    getActionWork(parsed.query).then(value => { if (current) setResult(value); }).catch(reason => { if (current) setError(reason instanceof ApiError && reason.status === 403 ? "Staff access is required." : "Actions could not be loaded. Try again."); }).finally(() => { if (current) setBusy(false); });
    return () => { current = false; };
  }, [urlSearch, refresh]);
  const change = (patch: Partial<WorkQuery>) => onNavigate(`/staff/actions${listSearch({ ...parsed.query, ...patch })}`);
  return <section className="queue-page action-work-page"><p className="eyebrow">Staff work</p><h1 ref={heading} tabIndex={-1}>My Actions</h1><p className="page-intro">Applied filters: {parsed.query.assignedTo ? "Assigned to me" : parsed.query.performedBy ? "Performed by me" : "All accessible actions"}{parsed.query.stateGroup ? " · Active current-cycle work on active Tickets" : parsed.query.state ? ` · ${parsed.query.state}` : ""}. Times use Bangkok.</p>{parsed.query.performedSince && <p>Performed range: {parsed.query.performedSince} to {parsed.query.performedUntil} (captured dashboard range).</p>}
    <div className="dashboard-quick-actions"><button className="secondary-button" onClick={() => onNavigate("/staff/actions?assignedTo=me&stateGroup=active")}>My assigned work</button><button className="secondary-button" onClick={() => onNavigate("/staff/actions?performedBy=me&state=COMPLETED")}>My performed work</button><button className="text-button" onClick={() => onNavigate("/staff/actions")}>Clear filters</button></div>
    {(parsed.error || error) && <div className="feedback-panel feedback-panel-error" role="alert">{parsed.error || error}{!parsed.error && <button className="secondary-button" onClick={() => setRefresh(n => n + 1)}>Retry actions</button>}</div>}
    {busy && <p role="status">Loading actions…</p>}{result && <><p role="status">{result.total} actions · Page {result.page} of {result.totalPages}</p>{result.items.length ? <table className="queue-table"><caption>Actions matching these work filters</caption><thead><tr>{["Ticket / Action", "State / Cycle", "Assignee", "Performed by / at", "Open"].map(t => <th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{result.items.map(a => <tr key={a.id}><td data-label="Ticket / Action"><strong>{a.ticketNumber} · Action {a.actionNumber}</strong><p>{a.summary}</p></td><td data-label="State / Cycle">{a.state.replaceAll("_", " ")} · Cycle {a.cycle}</td><td data-label="Assignee">{a.assignee?.displayName ?? "Unassigned"}</td><td data-label="Performed by / at">{a.performedBy?.displayName ?? "Not recorded yet"}{a.performedAt && <p>{new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Bangkok", dateStyle: "medium", timeStyle: "short" }).format(new Date(a.performedAt))}</p>}</td><td data-label="Open"><a className="secondary-button" href={`/staff/tickets/${a.ticketId}?tab=actions&actionId=${a.id}`} onClick={e => { e.preventDefault(); onNavigate(`/staff/tickets/${a.ticketId}?tab=actions&actionId=${a.id}`); }}>View Action {a.actionNumber}</a></td></tr>)}</tbody></table> : <p>No actions match these filters.</p>}<nav className="queue-pagination" aria-label="Action work pages"><button className="secondary-button" disabled={result.page <= 1} onClick={() => change({ page: result.page - 1 })}>Previous</button><button className="secondary-button" disabled={result.page >= result.totalPages} onClick={() => change({ page: result.page + 1 })}>Next</button><label>Actions per page<select value={parsed.query.pageSize} onChange={e => change({ pageSize: Number(e.target.value), page: 1 })}>{[10, 20, 50].map(n => <option key={n}>{n}</option>)}</select></label></nav></>}
  </section>;
}
