import { vi } from "vitest";
import * as dashboard from "../../src/dashboard-api.js";
import { ticketStatuses, type CurrentUser } from "../../src/api.js";
export const dashboardUser: CurrentUser = { id: 1, displayName: "Anan", email: "fixture@example.test", role: "REQUESTER", isActive: true, mustChangePassword: false };
const asOf = "2026-10-10T12:00:00.000Z", recentFrom = "2026-10-03T12:00:00.000Z";
const range = new URLSearchParams({ updatedSince: recentFrom, updatedUntil: asOf });
export const requesterDashboard = (): dashboard.RequesterDashboardData => ({ asOf, recentFrom, metrics: { activeTickets: 0, waitingForMe: 0, recentlyUpdated: 0, recentlyResolved: 0 }, recentTickets: [], attentionTickets: [], drillDown: { activeTickets: "/tickets?statusGroup=active", waitingForMe: "/tickets?status=WAITING_FOR_REQUESTER", recentlyUpdated: `/tickets?${range}`, recentlyResolved: `/tickets?${new URLSearchParams({ status: "RESOLVED", resolvedSince: recentFrom, resolvedUntil: asOf })}`, recentTickets: `/tickets?${range}`, attentionTickets: "/tickets?status=WAITING_FOR_REQUESTER" } });
export const staffDashboard = (): dashboard.StaffDashboardData => ({ asOf, recentFrom, metrics: { unassignedTickets: 0, myTickets: 0, myAssignedActions: 0, statusCounts: Object.fromEntries(ticketStatuses.map(s => [s, 0])) as dashboard.StaffDashboardData["metrics"]["statusCounts"], priorityCounts: { LOW: 0, MEDIUM: 0, HIGH: 0 } }, recentTickets: [], recentPerformedActions: [], drillDown: { unassignedTickets: "/staff/tickets?statusGroup=active&unassigned=true", myTickets: "/staff/tickets?statusGroup=active&ownerId=1", myAssignedActions: "/staff/actions?assignedTo=me&stateGroup=active", statusCounts: Object.fromEntries(ticketStatuses.map(s => [s, `/staff/tickets?status=${s}`])) as dashboard.StaffDashboardData["drillDown"]["statusCounts"], priorityCounts: { LOW: "/staff/tickets?statusGroup=active&itPriority=LOW", MEDIUM: "/staff/tickets?statusGroup=active&itPriority=MEDIUM", HIGH: "/staff/tickets?statusGroup=active&itPriority=HIGH" }, recentTickets: `/staff/tickets?${range}`, recentPerformedActions: `/staff/actions?${new URLSearchParams({ performedBy: "me", state: "COMPLETED", performedSince: recentFrom, performedUntil: asOf })}` } });
export function mockDashboards() { vi.spyOn(dashboard, "getRequesterDashboard").mockResolvedValue(requesterDashboard()); vi.spyOn(dashboard, "getStaffDashboard").mockResolvedValue(staffDashboard()); }
