import request from "supertest";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import { app } from "../../src/app.js";import { getPrisma } from "../../src/prisma.js";import { hashPassword } from "../../src/auth/password.js";import { seedDatabase } from "../../prisma/seed.js";
const db=getPrisma(),origin="http://localhost:5173",password="Communication-password-2026",suffix="@communication.example.test";let hash:string;
async function make(role:"REQUESTER"|"IT_STAFF"|"ADMINISTRATOR",name:string){return db.user.create({data:{displayName:name,email:`${Math.random()}${suffix}`,role,passwordHash:hash,mustChangePassword:false}})}
async function login(user:Awaited<ReturnType<typeof make>>){const agent=request.agent(app),csrf=(await agent.get("/api/auth/csrf")).body.csrfToken,r=await agent.post("/api/auth/login").set("Origin",origin).set("X-CSRF-Token",csrf).send({email:user.email,password});return{agent,token:r.body.csrfToken}}
async function setup(){const requester=await make("REQUESTER","Comment Requester"),foreign=await make("REQUESTER","Foreign Requester"),staff=await make("IT_STAFF","Comment Staff"),category=await db.category.findFirstOrThrow(),system=await db.relatedSystem.findFirstOrThrow(),ticket=await db.ticket.create({data:{ticketNumber:`OPS-COM-${Date.now()}`,requesterId:requester.id,categoryId:category.id,relatedSystemId:system.id,summary:"Communication",description:"Append only",requestedPriority:"LOW",itPriority:"LOW"}});return{requester,foreign,staff,ticket}}
beforeAll(async()=>{process.env.LEGACY_TEST_AUTH="disabled";await seedDatabase(db);hash=await hashPassword(password)});beforeEach(async()=>{await db.internalNote.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.publicComment.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.ticket.deleteMany({where:{ticketNumber:{startsWith:"OPS-COM-"}}});await db.user.deleteMany({where:{email:{endsWith:suffix}}})});afterAll(async()=>{await db.internalNote.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.publicComment.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.ticket.deleteMany({where:{ticketNumber:{startsWith:"OPS-COM-"}}});await db.user.deleteMany({where:{email:{endsWith:suffix}}});process.env.LEGACY_TEST_AUTH="enabled"});
describe("Public Comments and Internal Notes (AC-10)",()=>{it("keeps comments append-only, authored by the backend, and visible only with Ticket access",async()=>{const f=await setup(),owner=await login(f.requester),staff=await login(f.staff),foreign=await login(f.foreign);const posted=await owner.agent.post(`/api/tickets/${f.ticket.id}/comments`).set("Origin",origin).set("X-CSRF-Token",owner.token).send({body:"  Requester update <script>alert(1)</script>  "});expect(posted.status).toBe(201);expect(posted.body).toMatchObject({body:"Requester update <script>alert(1)</script>",author:{id:f.requester.id}});expect(posted.body).not.toHaveProperty("authorId");expect((await foreign.agent.get(`/api/tickets/${f.ticket.id}/comments`)).status).toBe(404);const visible=await staff.agent.get(`/api/tickets/${f.ticket.id}/comments`);expect(visible.body.items).toHaveLength(1);expect(JSON.stringify(visible.body)).not.toMatch(/password|internal/i);expect((await staff.agent.patch(`/api/tickets/${f.ticket.id}/comments/${posted.body.id}`).send({body:"edit"})).status).toBe(404)});it("validates comment bodies and pagination",async()=>{const f=await setup(),owner=await login(f.requester);for(const body of ["   ","x".repeat(4001)]){const r=await owner.agent.post(`/api/tickets/${f.ticket.id}/comments`).set("Origin",origin).set("X-CSRF-Token",owner.token).send({body});expect(r.status).toBe(400)}for(const query of ["page=0","pageSize=11","page=1&page=2","unknown=1"]){expect((await owner.agent.get(`/api/tickets/${f.ticket.id}/comments?${query}`)).status,query).toBe(400)}});it("restricts notes to Staff/Admin and never leaks them through Requester detail/comments",async()=>{const f=await setup(),owner=await login(f.requester),staff=await login(f.staff);expect((await owner.agent.get(`/api/staff/tickets/${f.ticket.id}/notes`)).status).toBe(403);const note=await staff.agent.post(`/api/staff/tickets/${f.ticket.id}/notes`).set("Origin",origin).set("X-CSRF-Token",staff.token).send({body:"Private diagnostic secret"});expect(note.status).toBe(201);expect(note.body.author.id).toBe(f.staff.id);expect((await staff.agent.get(`/api/staff/tickets/${f.ticket.id}/notes`)).body.items).toHaveLength(1);expect(JSON.stringify((await owner.agent.get(`/api/tickets/${f.ticket.id}`)).body)).not.toContain("Private diagnostic secret");expect(JSON.stringify((await owner.agent.get(`/api/tickets/${f.ticket.id}/comments`)).body)).not.toContain("Private diagnostic secret")})});
