import request from "supertest";
import { rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { app } from "../../src/app.js";
import { getPrisma } from "../../src/prisma.js";
import { hashPassword } from "../../src/auth/password.js";
import { seedDatabase } from "../../prisma/seed.js";
const db=getPrisma(), origin="http://localhost:5173", password="Operations-password-2026", suffix="@operations.example.test"; let hash:string;
const uploadRoot=fileURLToPath(new URL("../../uploads/",import.meta.url));
async function user(role:"REQUESTER"|"IT_STAFF"|"ADMINISTRATOR", name=role){return db.user.create({data:{displayName:name,email:`${name.replaceAll(" ","-").toLowerCase()}-${Math.random()}${suffix}`,role,passwordHash:hash,mustChangePassword:false}})}
async function login(account:Awaited<ReturnType<typeof user>>){const agent=request.agent(app),csrf=(await agent.get("/api/auth/csrf")).body.csrfToken;const r=await agent.post("/api/auth/login").set("Origin",origin).set("X-CSRF-Token",csrf).send({email:account.email,password});return{agent,token:r.body.csrfToken}}
async function fixture(status:"NEW"|"OPEN"|"IN_PROGRESS"|"WAITING_FOR_REQUESTER"|"RESOLVED"|"CLOSED"|"REOPENED"|"CANCELLED"="OPEN"){const requester=await user("REQUESTER","Operations Requester"),owner=await user("IT_STAFF","Operations Owner"),category=await db.category.findFirstOrThrow(),system=await db.relatedSystem.findFirstOrThrow();const ticket=await db.ticket.create({data:{ticketNumber:`OPS-${Date.now().toString().slice(-8)}-${Math.floor(Math.random()*999999)}`,requesterId:requester.id,categoryId:category.id,relatedSystemId:system.id,summary:"Operations fixture",description:"Safe detail",requestedPriority:"HIGH",itPriority:"MEDIUM",status}});return{requester,owner,ticket}}
beforeAll(async()=>{process.env.LEGACY_TEST_AUTH="disabled";await seedDatabase(db);hash=await hashPassword(password)});
beforeEach(async()=>{await db.internalNote.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.publicComment.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.ticket.deleteMany({where:{ticketNumber:{startsWith:"OPS-"}}});await db.user.deleteMany({where:{email:{endsWith:suffix}}})});
afterAll(async()=>{await db.internalNote.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.publicComment.deleteMany({where:{author:{email:{endsWith:suffix}}}});await db.ticket.deleteMany({where:{ticketNumber:{startsWith:"OPS-"}}});await db.user.deleteMany({where:{email:{endsWith:suffix}}});process.env.LEGACY_TEST_AUTH="enabled"});
const mutate=(agent:request.SuperAgentTest,token:string,path:string,method:"post"|"patch",body:unknown)=>agent[method](path).set("Origin",origin).set("X-CSRF-Token",token).send(body);
describe("Staff Ticket Detail operations (AC-08/09/11)",()=>{
 it("protects detail and returns safe operational context to Staff/Admin",async()=>{const f=await fixture();expect((await request(app).get(`/api/staff/tickets/${f.ticket.id}`)).status).toBe(401);const requester=await login(f.requester);expect((await requester.agent.get(`/api/staff/tickets/${f.ticket.id}`)).status).toBe(403);for(const role of ["IT_STAFF","ADMINISTRATOR"] as const){const actor=await user(role,`Detail ${role}`),s=await login(actor),r=await s.agent.get(`/api/staff/tickets/${f.ticket.id}`);expect(r.status).toBe(200);expect(r.body).toMatchObject({description:"Safe detail",version:1,owner:null,requesterResolutionIndicatedAt:null,attachments:[]});expect(JSON.stringify(r.body)).not.toMatch(/passwordHash|internalNote/i)}});
 it("claims atomically, rejects stale versions, and validates eligible reassignment",async()=>{const f=await fixture(),staff=await user("IT_STAFF","Claim Staff"),other=await user("ADMINISTRATOR","Assign Admin"),s=await login(staff);const [a,b]=await Promise.all([mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/claim`,"post",{version:1}),mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/claim`,"post",{version:1})]);expect([a.status,b.status].sort()).toEqual([200,409]);const claimed=[a,b].find(x=>x.status===200)!;expect(claimed.body).toMatchObject({owner:{id:staff.id},version:2});expect((await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/priority`,"patch",{itPriority:"LOW",version:1})).body.error.code).toBe("VERSION_CONFLICT");const reassigned=await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/owner`,"patch",{ownerId:other.id,version:2});expect(reassigned.body).toMatchObject({owner:{id:other.id},version:3});await db.user.update({where:{id:other.id},data:{isActive:false}});const invalid=await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/owner`,"patch",{ownerId:other.id,version:3});expect(invalid.status).toBe(400);expect(invalid.body.error.code).toBe("INVALID_OWNER")});
 it("changes priority and follows only approved transitions, including reopen clearing indication",async()=>{const f=await fixture("OPEN"),staff=await user("IT_STAFF","Transition Staff"),s=await login(staff);let r=await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/priority`,"patch",{itPriority:"HIGH",version:1});expect(r.body).toMatchObject({itPriority:"HIGH",version:2});r=await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/status`,"patch",{status:"RESOLVED",version:2});expect(r.body).toMatchObject({status:"RESOLVED",version:3});const invalid=await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/status`,"patch",{status:"IN_PROGRESS",version:3});expect(invalid.status).toBe(409);expect(invalid.body.error.code).toBe("INVALID_STATUS_TRANSITION");expect((await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/priority`,"patch",{itPriority:"LOW",version:3})).body.error.code).toBe("TICKET_TERMINAL");r=await mutate(s.agent,s.token,`/api/staff/tickets/${f.ticket.id}/status`,"patch",{status:"REOPENED",version:3});expect(r.body).toMatchObject({status:"REOPENED",version:4,requesterResolutionIndicatedAt:null})});
 it("records Requester resolution once, gives stale-version precedence, and never changes status",async()=>{const f=await fixture("OPEN"),r=await login(f.requester);let response=await mutate(r.agent,r.token,`/api/tickets/${f.ticket.id}/resolution-indication`,"post",{version:1});expect(response.body.status).toBe("OPEN");expect(response.body.version).toBe(2);expect(response.body.requesterResolutionIndicatedAt).toBeTruthy();const time=response.body.requesterResolutionIndicatedAt;response=await mutate(r.agent,r.token,`/api/tickets/${f.ticket.id}/resolution-indication`,"post",{version:2});expect(response.body).toMatchObject({version:2,requesterResolutionIndicatedAt:time});expect((await mutate(r.agent,r.token,`/api/tickets/${f.ticket.id}/resolution-indication`,"post",{version:1})).body.error.code).toBe("VERSION_CONFLICT");await db.ticket.update({where:{id:f.ticket.id},data:{status:"RESOLVED",version:3}});expect((await mutate(r.agent,r.token,`/api/tickets/${f.ticket.id}/resolution-indication`,"post",{version:2})).body.error.code).toBe("VERSION_CONFLICT");expect((await mutate(r.agent,r.token,`/api/tickets/${f.ticket.id}/resolution-indication`,"post",{version:3})).body.error.code).toBe("RESOLUTION_INDICATION_NOT_ALLOWED")});
 it("allows Staff to download active Attachment bytes but not removed content",async()=>{const f=await fixture(),staff=await user("IT_STAFF","Attachment Staff"),requester=await login(f.requester),s=await login(staff),png=Buffer.from("89504e470d0a1a0a","hex"),activeName=`ops-active-${f.ticket.id}.png`,removedName=`ops-removed-${f.ticket.id}.png`;try{await Promise.all([writeFile(`${uploadRoot}${activeName}`,png),writeFile(`${uploadRoot}${removedName}`,png)]);const [active,removed]=await Promise.all([db.attachment.create({data:{ticketId:f.ticket.id,originalName:"active.png",storedName:activeName,mimeType:"image/png",sizeBytes:png.length}}),db.attachment.create({data:{ticketId:f.ticket.id,originalName:"removed.png",storedName:removedName,mimeType:"image/png",sizeBytes:png.length,removedAt:new Date(),removalReason:"obsolete",removedByUserId:f.requester.id}})]);const download=await s.agent.get(`/api/staff/tickets/${f.ticket.id}/attachments/${active.id}/download`);expect(download.status).toBe(200);expect(download.headers["content-type"]).toMatch(/^image\/png/);expect(download.headers["content-disposition"]).toContain("active.png");expect(Buffer.compare(download.body,png)).toBe(0);expect((await s.agent.get(`/api/staff/tickets/${f.ticket.id}/attachments/${removed.id}/download`)).status).toBe(404);expect((await requester.agent.get(`/api/staff/tickets/${f.ticket.id}/attachments/${active.id}/download`)).status).toBe(403)}finally{await db.attachment.deleteMany({where:{ticketId:f.ticket.id}});await Promise.all([rm(`${uploadRoot}${activeName}`,{force:true}),rm(`${uploadRoot}${removedName}`,{force:true})])}});
});
